### ISSUE TITLE
onplayerrespawn

### ISSUE THREAD

**Issue by whistleman** [Ligthert/SL_Wild_Ravens.Chernarus#1]
line 11-14:
Maybe check how many positions/places are left in the vehicle, so when an entire squad gets nurfed and there are no more places left then you can place the units outside the vehicle or on another respawnpos/car?

**Comment by Ligthert** [comment]
The good news is: 5 players in ArmA usually don't die at the same time causing them to fill up the old war horse. :) It is with 6 players where things get interesting...

**Comment by Ligthert** [comment]
I am closing this ticket for several reasons:
1. The offending lines have been removed based on the findings after the first play testing.
2. The "respawn" marker is placed behind the car
3. Future implementations should have a more complex respawn placement. What doesn't help is that ArmA treats new players during restart as a respawn fucking up your player placement.
