### ISSUE TITLE
init.sqf

### ISSUE THREAD

**Issue by whistleman** [Ligthert/SL_Wild_Ravens.Chernarus#2]
Enemyunits.sqf does not have to be known by the clients.

So instead of:
`#include "enemyUnits.sqf";`
` `
`// TODO: What about the HC slot?`
`if (isServer) then {`
`execVM "genMissions.sqf";`
`};`

do:
`// TODO: What about the HC slot?`
`if (isServer) then {`
`execVM "genMissions.sqf";`
`#include "enemyUnits.sqf";`
`};`

**Comment by Ligthert** [comment]
It depends. I was looking into having groups offloaded to the clients instead of the HC. This should fix my scaling issue. ;)

**Comment by Ligthert** [comment]
nodes[] is also global. Which is only needed on the locality running the missions. Will fix. :)
